name: time_tracking_to_do
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.3.0

dependencies:
  #B
  bloc: ^8.1.4
  #D
  dartz: ^0.10.1
  #F
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  #G
  get_it: ^8.0.2
  #H
  http: ^1.2.2
  #I
  intl: ^0.19.0
  #S
  flutter_spinkit: ^5.2.1
  #U
  uuid: ^4.5.1

  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
